Unhappy path experience
Bora-CS/batch8-cucumber-base pull request #4
Opened 2022-09-03 20:11 UTC by LixiaSun

Unhappy path add experience

2022-09-03 20:16 UTC, Muradil-Erkin requested changes

2022-09-03 20:16 UTC, Muradil-Erkin commented on src/test/resources/features/apiaddexperience.feature
> +    Then user enters incorrect add experience inputs
- This step should just enter experience details, regardless if it's valid or invalid.
- All API steps should have `[API]` prefix

2022-09-03 20:16 UTC, Muradil-Erkin commented on src/test/resources/features/apiaddexperience.feature
> +    Then user gets back error(s)
Expected errors should be 1 single field:
`| Title is required, Company is required, From date is required |`

2022-09-03 20:16 UTC, Muradil-Erkin commented on src/test/resources/features/AddExperience.feature
> +    Then user should see the success alert
This file should be deleted

2022-09-03 20:16 UTC, Muradil-Erkin commented on src/test/java/runners/APIUnhappyPathRunner.java
> +}
This file can be deleted

2022-09-03 20:16 UTC, Muradil-Erkin commented on src/test/java/apiStepDefinitions/Profile.java
> +	   response = request.body(experience.keySet()).put("/api/profile/experience");
API implementation should be extracted to classes under `api/xxxx.java`

2022-09-03 20:16 UTC, Muradil-Erkin commented on src/test/java/apiStepDefinitions/Profile.java
> +}
Files should be formatted

2022-09-03 20:16 UTC, Muradil-Erkin commented on src/test/java/apiStepDefinitions/Profile.java
> +	 final static int expectedUnhappyStatusCode = 400;
Constants should go under a file `utilities/constants.java`

2022-09-05 21:39 UTC, closed without merging

2022-09-05 21:41 UTC, LixiaSun commented
Accidentally deleted the branch, and created  a new pull request.